---
version: "2"

services:
  parser:
    build: .
    environment:
      - MODE=dev
    volumes:
      - .:/app
      - /var/log/project_log:/app/instance/log
    ports:
      - "8000:8000"
      - "3306:3306"