---
version: "2"

services:
  parser:
    build: .
    environment:
      - MODE=dev
    volumes:
      - /var/log/project_log:/app/instance/log
    ports:
      - "8000:8000"
    network_mode: "host"
