"""empty message

Revision ID: 1e2659f5ccc4
Revises: e3eb6893cd9d
Create Date: 2018-06-07 11:54:39.648965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2659f5ccc4'
down_revision = 'e3eb6893cd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_meta', sa.Column('country', sa.String(length=250), nullable=True))
    op.add_column('search', sa.Column('import_source_id', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'import_source_id')
    op.drop_column('resource_meta', 'country')
    # ### end Alembic commands ###
