"""empty message

Revision ID: 29a5263e61e3
Revises: 740ee97161e8
Create Date: 2018-06-06 12:36:45.761727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a5263e61e3'
down_revision = '740ee97161e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_data', sa.Column('import_source_id', sa.String(length=250), nullable=True))
    op.add_column('parsed_data', sa.Column('raw_page_html', sa.Text(), nullable=True))
    op.drop_column('parsed_data', 'mw_id')
    op.add_column('search', sa.Column('import_source_id', sa.String(length=250), nullable=True))
    op.add_column('search', sa.Column('page_link', sa.String(length=250), nullable=True))
    op.drop_column('search', 'parsed_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('parsed_page', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('search', 'page_link')
    op.drop_column('search', 'import_source_id')
    op.add_column('parsed_data', sa.Column('mw_id', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('parsed_data', 'raw_page_html')
    op.drop_column('parsed_data', 'import_source_id')
    # ### end Alembic commands ###
