"""empty message

Revision ID: 4b6c521a1bf5
Revises: fdb680fae131
Create Date: 2018-06-08 14:42:45.028102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b6c521a1bf5'
down_revision = 'fdb680fae131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('uri', sa.String(length=250), nullable=False))
    op.drop_column('resource', 'relative_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('relative_path', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('resource', 'uri')
    # ### end Alembic commands ###
