"""empty message

Revision ID: 614704e54da9
Revises: 157175f2f267
Create Date: 2018-06-09 13:02:00.347012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '614704e54da9'
down_revision = '157175f2f267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('kinopoisk_id', sa.String(length=250), nullable=True),
    sa.Column('import_source_id', sa.String(length=250), nullable=True),
    sa.Column('raw_page_data', sa.UnicodeText(length=4294000000), nullable=True),
    sa.Column('raw_page_html', sa.UnicodeText(length=4294000000), nullable=True),
    sa.Column('quality', sa.String(length=250), nullable=True),
    sa.Column('format', sa.String(length=250), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('size', sa.String(length=250), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('title_ru', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(length=250), nullable=True),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('subtitle_format', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('casting', sa.Text(), nullable=True),
    sa.Column('video_info', sa.Text(), nullable=True),
    sa.Column('audio_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('download_meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_meta',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('search_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kinopoisk_id', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('import_source_id', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('raw_page_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('raw_page_html', mysql.LONGTEXT(), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('format', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title_en', mysql.TEXT(), nullable=True),
    sa.Column('title_ru', mysql.TEXT(), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('translation', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('subtitle', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('subtitle_format', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('gender', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('casting', mysql.TEXT(), nullable=True),
    sa.Column('video_info', mysql.TEXT(), nullable=True),
    sa.Column('audio_info', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], name='download_meta_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('parsed_data')
    # ### end Alembic commands ###
