"""empty message

Revision ID: 70b3d8a39032
Revises: 28ec4a87eb4c
Create Date: 2018-07-25 15:55:11.287561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70b3d8a39032'
down_revision = '28ec4a87eb4c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('search', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('download', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('search_id', sa.BigInteger(), nullable=True))
    op.drop_column('resource', 'episode_title')
    op.drop_column('resource', 'domain')
    op.drop_column('resource', 'episode_no')
    op.drop_column('resource', 'uri')
    op.add_column('resource_media', sa.Column('episode_no', sa.Integer(), nullable=True))
    op.add_column('resource_media', sa.Column('episode_title', sa.UnicodeText(), nullable=False))
    op.add_column('resource_media', sa.Column('url', sa.String(length=250), nullable=False))
    op.alter_column('resource_media', 'status',
               existing_type=mysql.ENUM('NOT_REENCODED', 'REENCODING', 'NOT_DEPLOYED', 'READY'),
               type_=sa.Enum('NOT_ENCODED', 'ENCODING', 'NOT_DEPLOYED', 'READY', name='statuses'),
               existing_nullable=True)
    op.drop_column('resource_media', 'domain')
    op.drop_column('resource_media', 'relative_path')
    # ### end Alembic commands ###


def downgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_media', sa.Column('relative_path', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('resource_media', sa.Column('domain', mysql.VARCHAR(length=250), nullable=True))
    op.alter_column('resource_media', 'status',
               existing_type=sa.Enum('NOT_ENCODED', 'ENCODING', 'NOT_DEPLOYED', 'READY', name='statuses'),
               type_=mysql.ENUM('NOT_REENCODED', 'REENCODING', 'NOT_DEPLOYED', 'READY'),
               existing_nullable=True)
    op.drop_column('resource_media', 'url')
    op.drop_column('resource_media', 'episode_title')
    op.drop_column('resource_media', 'episode_no')
    op.add_column('resource', sa.Column('uri', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('resource', sa.Column('episode_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('domain', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('resource', sa.Column('episode_title', mysql.TEXT(), nullable=False))
    op.drop_column('resource', 'search_id')
    # ### end Alembic commands ###

