"""empty message

Revision ID: 740ee97161e8
Revises: e28ea2445ee0
Create Date: 2018-06-04 16:15:18.088434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740ee97161e8'
down_revision = 'e28ea2445ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('download_rate_kb', sa.Float(), nullable=True),
    sa.Column('upload_rate_kb', sa.Float(), nullable=True),
    sa.Column('num_peers', sa.Integer(), nullable=True),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('torrent_state', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('downloaded_at', sa.Date(), nullable=True),
    sa.Column('save_path', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    # ### end Alembic commands ###
