"""empty message

Revision ID: 7f5c8801e13c
Revises: 7c6f70660b7c
Create Date: 2018-06-14 11:35:29.610813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f5c8801e13c'
down_revision = '7c6f70660b7c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_data', 'raw_page_html')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_data', sa.Column('raw_page_html', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def upgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

