"""empty message

Revision ID: a97f4e5cd38b
Revises: c8b81ac57481
Create Date: 2018-07-25 14:13:07.386931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a97f4e5cd38b'
down_revision = 'c8b81ac57481'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('search', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('download', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('type', sa.Enum('MOVIE', 'SERIES', name='resourcetype'), nullable=False))
    op.create_index(op.f('ix_resource_type'), 'resource', ['type'], unique=False)
    op.drop_index('ix_resource_types', table_name='resource')
    op.drop_column('resource', 'types')
    op.add_column('resource_media', sa.Column('extension', sa.String(length=250), nullable=False))
    op.add_column('resource_media', sa.Column('file_type', sa.Enum('VIDEO', 'SUBTITLE', 'AUDIO', name='filetypes'), nullable=False))
    op.create_index(op.f('ix_resource_media_file_type'), 'resource_media', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_media_file_type'), table_name='resource_media')
    op.drop_column('resource_media', 'file_type')
    op.drop_column('resource_media', 'extension')
    op.add_column('resource', sa.Column('types', mysql.ENUM('MOVIE', 'SERIES'), nullable=False))
    op.create_index('ix_resource_types', 'resource', ['types'], unique=False)
    op.drop_index(op.f('ix_resource_type'), table_name='resource')
    op.drop_column('resource', 'type')
    # ### end Alembic commands ###

