"""empty message

Revision ID: b8af15b16e51
Revises: ff45c83d47a2
Create Date: 2018-06-09 16:20:44.672009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8af15b16e51'
down_revision = 'ff45c83d47a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download', 'torrent_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('torrent_state', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
