"""empty message

Revision ID: cf40e4a33972
Revises: 6fd2a1ee93cd
Create Date: 2018-07-26 14:53:33.710642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf40e4a33972'
down_revision = '6fd2a1ee93cd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('search', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'gender',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('download', 'error',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'json_meta',
               existing_type=mysql.LONGTEXT(),
               type_=sa.UnicodeText(length=4294000000),
               existing_nullable=True)
    op.add_column('resource_media', sa.Column('parent_folder', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_media', 'parent_folder')
    op.alter_column('resource', 'json_meta',
               existing_type=sa.UnicodeText(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###

