"""empty message

Revision ID: e28ea2445ee0
Revises: d8dfcf457c5b
Create Date: 2018-06-04 15:18:47.378227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28ea2445ee0'
down_revision = 'd8dfcf457c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parsed_data', 'search', ['search_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parsed_data', type_='foreignkey')
    # ### end Alembic commands ###
