"""empty message

Revision ID: e3eb6893cd9d
Revises: 29a5263e61e3
Create Date: 2018-06-06 13:15:13.872569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3eb6893cd9d'
down_revision = '29a5263e61e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_meta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('kinopoisk_id', sa.String(length=250), nullable=True),
    sa.Column('import_source_id', sa.String(length=250), nullable=True),
    sa.Column('raw_page_data', sa.Text(), nullable=True),
    sa.Column('raw_page_html', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=250), nullable=True),
    sa.Column('format', sa.String(length=250), nullable=True),
    sa.Column('size', sa.String(length=250), nullable=True),
    sa.Column('title_en', sa.String(length=250), nullable=True),
    sa.Column('title_ru', sa.String(length=250), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(length=250), nullable=True),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('subtitle_format', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('casting', sa.String(length=250), nullable=True),
    sa.Column('video_info', sa.String(length=250), nullable=True),
    sa.Column('audio_info', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parsed_data')
    op.add_column('search', sa.Column('raw', sa.Text(), nullable=True))
    op.drop_column('search', 'import_source_id')
    op.drop_column('search', 'extra_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('extra_json', mysql.TEXT(), nullable=True))
    op.add_column('search', sa.Column('import_source_id', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('search', 'raw')
    op.create_table('parsed_data',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('kinopoisk_id', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('raw_page_data', mysql.TEXT(), nullable=True),
    sa.Column('quality', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('format', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title_en', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title_ru', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('translation', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('subtitle', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('subtitle_format', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('casting', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_info', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('audio_info', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('search_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('import_source_id', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('raw_page_html', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], name='parsed_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('resource_meta')
    # ### end Alembic commands ###
