"""empty message

Revision ID: f7ffa5626243
Revises: bf4157c11114
Create Date: 2018-07-24 16:53:06.639334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ffa5626243'
down_revision = 'bf4157c11114'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_media', sa.Column('status', sa.Enum('NOT_REENCODED', 'REENCODING', 'NOT_DEPLOYED', 'READY', name='statuses'), nullable=True))
    # ### end Alembic commands ###


def downgrade_db_resource():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_media', 'status')
    # ### end Alembic commands ###

