"""empty message

Revision ID: fdb680fae131
Revises: 3d66f6df3fbb
Create Date: 2018-06-07 17:42:22.459349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdb680fae131'
down_revision = '3d66f6df3fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'domain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('resource', 'episode_title',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('resource', 'relative_path',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('resource', 'system_path',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.add_column('resource_media', sa.Column('mime', sa.String(length=250), nullable=False))
    op.alter_column('resource_media', 'resource_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.drop_column('resource_media', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_media', sa.Column('format', mysql.VARCHAR(length=250), nullable=True))
    op.alter_column('resource_media', 'resource_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.drop_column('resource_media', 'mime')
    op.alter_column('resource', 'system_path',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('resource', 'relative_path',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('resource', 'episode_title',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('resource', 'domain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
