---
- name: Deployment
  hosts: staging
  vars:
    project_path: "/var/www/{{app_name}}"
    project_instance_path: "{{project_path}}/instance"
    env_path: "{{project_path}}/.env"
    python: "{{env_path}}/bin/python"
  environment:
    FLASK_APP: "{{project_path}}/app.py"
    FLASK_DEBUG: 0
  tasks:
    - name: update repo
      git:
        repo: https://f3l1s@bitbucket.org/8bitgroup/bt-lostplanet.git
        dest: "{{project_path}}"
        version: master
        update: yes
      notify:
        - run migrations
    - name: init folders
      file:
        path:
          - "{{project_instance_path}}"
        state: directory
        mode: 0755
    - name: copy application configs
      template:
        src=../files/instance/config.py
        dest="{{project_path}}/instance/config.py"
    - name: run pip install
      pip:
        requirements: "{{project_path}}/requirements.txt"
        virtualenv: "{{env_path}}"
        virtualenv_python: python3
    - name: copy supervisor conf
      template: src=../files/inssupervisor.conf dest="{{project_instance_path}}" mode=0644
  handlers:
    - name: run migrations
      shell: "cd {{project_path}} && {{env_path}}/bin/flask db upgrade"