---
- name: Deployment
  hosts: production
  vars:
    project_path: "/var/www/{{ app_name }}"
    project_instance_path: "{{ project_path }}/instance"
    env_path: "{{ project_path }}/.env"
    python: "{{ env_path }}/bin/python"
  tasks:
    - name: update repo
      git:
        repo: git@bitbucket.org:8bitgroup/bt-lostplanet.git
        dest: "{{ project_path }}"
        version: master
        accept_hostkey: True
        update: True
      notify:
        - build docker
        - down docker
        - up docker

    - name: init folders
      file:
        path="{{ item.path }}"
        state=directory
        mode="{{ item.mode }}"
      with_items:
        - { path: '{{ project_instance_path }}', mode: '0744' }
        - { path: '{{ project_instance_path }}/log', mode: '0777' }

    - name: copy instance files
      template:
        src=../files/instance/{{ item }}
        dest="{{ project_instance_path }}/{{ item }}"
        force=True
        mode=0755
      with_items:
        - config.py
        - supervisor.conf
        - entrypoint.sh

  handlers:
    - name: build docker
      command: "docker-compose build"
      args:
        chdir: "{{project_path}}"
    - name: down docker
      command: "docker-compose down"
      args:
        chdir: "{{project_path}}"
    - name: up docker
      command: "docker-compose up -d"
      args:
        chdir: "{{project_path}}"


##    need pip to install docker-compose, apt version does not work. commented for now
#    - name: run docker
#      docker_service:
#        project_name: parser
#        definition:
#          version: '2'
#          services:
#            parser:
#              build: "{{ project_path }}"
#              volumes:
#                - /var/log/project_log:/app/instance/log
#              network_mode: "host"