"""empty message

Revision ID: 981f6dcc6024
Revises: 417110295a7c
Create Date: 2018-09-06 11:10:01.230378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '981f6dcc6024'
down_revision = '417110295a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_data', sa.Column('changed_at', sa.DateTime(), nullable=False))
    op.add_column('parsed_data', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('parsed_data', sa.Column('download_status', sa.Enum('NOT_SEND', 'SEND', 'DOWNLOADED', name='downloadstatuses'), nullable=False))
    op.add_column('parsed_data', sa.Column('next_update_at', sa.DateTime(), nullable=True))
    op.alter_column('parsed_data', 'audio_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'genre',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('parsed_data', 'video_info',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.create_index(op.f('ix_parsed_data_download_status'), 'parsed_data', ['download_status'], unique=False)
    op.alter_column('search', 'error',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    op.alter_column('search', 'raw',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search', 'raw',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('search', 'error',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_parsed_data_download_status'), table_name='parsed_data')
    op.alter_column('parsed_data', 'video_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'title',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'raw_page_data',
               existing_type=sa.Text(length=16000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'magnet_link',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'genre',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'description',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'casting',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('parsed_data', 'audio_info',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.drop_column('parsed_data', 'next_update_at')
    op.drop_column('parsed_data', 'download_status')
    op.drop_column('parsed_data', 'created_at')
    op.drop_column('parsed_data', 'changed_at')
    # ### end Alembic commands ###
